import AppProvider from "@/context/AppProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CRUD with Firebase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Navbar />
          <main className="sm:px-0 container px-5 mx-auto">{children}</main>
        </AppProvider>
      </body>
    </html>
  );
}
